### PR TITLE
Ensure that include(FindPackageHandleStandardArgs) is called before f…

### PR DESCRIPTION
**Pull request by DJDavies2**
Another attempt at a pull request for https://github.com/JCSDA/ecbuild/issues/13

### CODE REVIEW

**Comment by mmiesch** [comment]
This generally looks ok to me as something that work, though I don't know if this is the best place for it.  It does look like the include statement is included before most of the calls wherever it appears in ecbuild so in that sense it's appropriate

**Comment by mmiesch** [comment]
I just tested this and it doesn't work for me.  I was able to reproduce your lapack error but when I use this branch of ecbuild, I still get the error.

**Comment by mmiesch** [comment]
Actually - I guess I wasn't able to reproduce your error.  The error I get with both this branch and release/stable is just
~~~~~
-- Found Threads: TRUE  
CMake Error at /opt/modules/core/cmake/3.13.0/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /opt/modules/core/cmake/3.13.0/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /opt/modules/core/cmake/3.13.0/share/cmake-3.13/Modules/FindBLAS.cmake:733 (find_package_handle_standard_args)
  /opt/modules/core/cmake/3.13.0/share/cmake-3.13/Modules/FindLAPACK.cmake:163 (find_package)
  oops/CMakeLists.txt:65 (find_package)


-- Configuring incomplete, errors occurred!
~~~~~
...which is the same error I get if I omit the lapack_path argument altogether.  But this works:
~~~~~
ecbuild -DLAPACK_LIBRARIES=$LPATH/liblapack.a -DBLAS_LIBRARIES=$LPATH/libblas.a ../src/ufo-bundle
~~~~~

**Comment by DJDavies2** [comment]
How did you build Lapack?  I built it via its cmake build, generating shared libraries.  I see you are using static libraries.

**Comment by DJDavies2** [comment]
So to expand on the above, my Lapack is built like this:

tar zxf lapack-3.8.0.tar.gz
cmake lapack-3.8.0 -DBUILD_SHARED_LIBS=ON ...
make
make install

**Comment by mmiesch** [comment]
@markjolah - I was not having LAPACK problems - if I load my lapack module everything is fine - I was merely trying to reproduce this issue and I cannot.  I was just trying to understand it a bit better before I approve.  The include statements appear before the calls in the Find<pkg>.cmake modules but it seems they were deliberately left out of the ecbuild_find_omp.cmake and ecbuild_find_python.cmake modules.  I was trying to figure out if this is supposed to get set higher up in the ecbuild heirarchy, like ecbuild_system or ecbuild_install_project

**Comment by markjolah** [comment]
So CMake macros expand inline and pollute the scope.  Also all find_package() commands that end up calling a find module FindXYZ.cmake will expand inline and pollute the scope.  Almost any Find module will use FindPackageHandleStandardArgs.  If another find module is called first it will process the include, and the global scope will now include ` find_package_handle_standard_args`.  Later the call to `ecbuild_find_omp` will appear to work fine, but this is just coincidence, and it is still a bug.  As soon as `ecbuild_find_omp` is called before any other macro or `find_package` command that processes the necessary include, this bug will re-emerge.

**Comment by markjolah** [comment]
In reference to you last point, it's always incorrect to call a function from a module that has not been explicitly included in the local scope.  There is no harm in multiple includes of the same file.  However missing the include leads to these types of finicky bugs which may be impossible to reproduce unless you have exactly the same environment.  If there are other locations where this same pattern occurs they also need to have the include statement.

**Comment by mmiesch** [comment]
Ok - Thanks @markjolah - you convinced me.  I still don't see why it solves the original LAPACK problem but I'm good with it.

**Pull request merged**
