### PR TITLE
Feature/ecmwf synch

### PR DESCRIPTION
**Pull request by mmiesch**
Synch with ecmwf develop

### CODE REVIEW

**Comment by mmiesch** [comment]
@aerorahul had some concerns if jedi was ready for the latest ecbuild functionality but I've been using this brach for the intel17 and intel19 stacks on S4 and everything looks fine as far as I can tell.  I'd like to merge this PR before defining another tagged release and using that to build new containers.

**Comment by aerorahul** [comment]
I think the newer version of ecbuild (post v3) allows deprecated usage of ecbuild (v2).  So I think we are safe.
We should however progress towards updating our CMakeLists.txt in our projects to be ecbuild v3 compliant.  This will take time.  I believe @markjolah has begun that with SABER.

**Comment by DJDavies2** [comment]
How are people finding NetCDF with this ecbuild?  I tried 3.3.0.jscda1 with lfric-bundle and it failed like this:

CMake Error at ecbuild/cmake/FindNetCDF.cmake:223 (add_library):
  add_library called with IMPORTED argument but no library type.
Call Stack (most recent call first):
  saber/CMakeLists.txt:63 (find_package)


CMake Error at ecbuild/cmake/FindNetCDF.cmake:224 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  NetCDF::NetCDF_Fortran
Call Stack (most recent call first):
  saber/CMakeLists.txt:63 (find_package)

It worked with 3.1.0.

**Comment by aerorahul** [comment]
I think I found a similar issue and have a fix. 
I need to test it on discover. 
The issue I noted is with cflags and the removal of -I.
I replaced cflags with includedir and that resolved the issue. I also didn’t need be REPLACE function.  
Expect a bugfix shortly.

**Pull request merged**
