### PR TITLE
Minor fixes for Fortran+NetCDF support.

### PR DESCRIPTION
**Pull request by tclune**
1) Fortran was not consistently capitalized internally, and was
   generally conflicting with the cmake convention "Fortran" not "FORTRAN".

2) When removing duplicates in the library list, it is important to
   recognize that there are "debug" libs and "optimized" libs, and the
   duplicates should be removed separately from each rather than mixed
   together.  This is masked by higher levels of ecbuild which strip
   out these options.

There remain other harder issues that must eventually be fixed.  E.g.,
The Fortran "debug" library list is empty which is not a supported
capability for cmake.

And of course the higher levels of cmake are removing duplicates
incorrectly as well.  They should use the same reverse-remove-reverse
pattern, and must be cognizant of debug/optimized issues.  I actually
think that ecbuild should _not_ remove duplicates, but maybe there
were good reasons for this.  But the existing practice definitely gets
it wrong for NetCDF prior to the other workarounds in the NetCDF
layer.

### CODE REVIEW

**Comment by tclune** [comment]
To be fair,  I mostly fixed the capitalization while trying to find the real culprit for why this layer was not working for me.   I personally would (mildly) advocate adding additional output variables to be more consistent with CMake.    And as much as I enjoy berating  people that spell Fortran as FORTRAN,  I really wish that CMake had used all caps in this context.  But fixing ecbuild seems more probable than fixing CMake at this point.

I can live with the existing capitalizations.   The real issue here is the need to have the FindNetCDF package work when ECBUILD_2_COMPAT is set to OFF.    This is required for GEOS because the latest release of cmake changed a few things from warnings (undesirable) into errors.

**Comment by markjolah** [comment]
OK.  Completely removing the CMake 2.x support (and the numerous warnings and odious constraints on CMake syntax that it 2.x support implies) is on my medium-term goals for the ecbuild repo.  As far as I can tell most JEDI users are using much more recent CMake versions.

We are currently using CMake 3.13 in the jedi-stack which is now used to build both the lmod modules system and the docker/singularity/charliecloud containers.  What version of CMake are you using with GEOS?

I will try to test with `ECBUILD_2_COMPAT=off` and see what happens.

**Comment by tclune** [comment]
We are using 3.14.1 which is where we encounter the more severe issues.   3.13 only provided warnings.  And of course, I did all my prep work on my laptop with 3.13 which then broke when I asked others to try it on the cluster.

**Comment by markjolah** [comment]
OK I am using 3.14.5 on my laptop, so I should be able to help debug any other ecbuild/CMake-3.14+ issues.  In the process of trying to clean up some of these issues, I've discovered some other deficiencies in the FindNetCDF4.cmake script.  I am closing this PR and merging it with the new issue #8, which will collect all known issues with NetCDF4 support in ecbuild.  @tclune: Please comment there if you have any other issues I didn't summarize.

**Pull request closed without merging**
