### PR TITLE
feature/netcdf4-cmake

### PR DESCRIPTION
**Pull request by aerorahul**
rely on nc-config to gather includes and libraries for netcdf.

technically FindHDF4.cmake is not required, but since I went through the effort of putting together one, adding it here.

### CODE REVIEW

**Comment by markjolah** [comment]
(Copy of my emailed questions sent to Rahul so as to keep discussion in github)

A couple of issues/questions:
1. What is going on with the sequence:

 list( REVERSE NETCDF_LIBRARIES_DEBUG )
 list( REMOVE_DUPLICATES NETCDF_LIBRARIES_DEBUG )
 list( REVERSE NETCDF_LIBRARIES_DEBUG )

Logically, this seems like the double reversal is a NO-OP?  Are you working around a CMake bug with list(REMOVE_DUPLICATES) on some system?

2. I saw you removed the HDF5 find_package() commands to clean up the old code that sets NETCDF_IS_PARALLEL.  But whatever still remains from the old code seems broken.  nc-config has actually three flags to check for parallel support (--has-parallel --has-parallel4 and --has-pnetcdf).  I can fix up this section, and propose to correctly set three CMake variables that match with the nc-config meanings:

NETCDF_IS_PARALLEL3 - True if built with pnetcdf support for v3 files
NETCDF_IS_PARALLEL4 - True if built with parallel support for v4 files
NETCDF_IS_PARALLEL - True if either PARALLEL3 or PARALLEL4 support exists (this def matches the meaning of nc-config --has-parallel)

**Comment by aerorahul** [comment]
@markjolah Thanks for the review.

1. I am glad you noticed this hack. `REMOVE_DUPLICATES` in `cmake` retains the 1st entry and removes all the rest from a list.  In the instance that `NetCDF` is built with all the bells and whistles e.g. `HDF4`, `HDF5` and each with a custom location of dependencies e.g. `jasper`, `libjasper` appears after `libhdf`, `libhdf_hl`, `libhdf5`.
`REMOVE_DUPLICATES` will retain the first occurrence, and remove the rest.
During linking, if any of the hdf libraries are after the `libjasper`, they will complain about a missing `libjasper`.  Reversing and then removing the duplicates and then reversing again keeps them.  It certainly is a hack, and so if you or anyone has a better solution, I'ld be happy to test.

2. Thank you for offering to fix these issues.  I was unaware of these.  Just to keep in mind, this is `FindNetCDF4.cmake`, and thus `NETCDF_IS_PARALLEL3` does not belong here.

**Comment by aerorahul** [comment]
@markjolah 
I fixed the `nc-config --has-parallel` issue to obtain if `netcdf4` is built with parallel support (not via pnetcdf; that is checked later`).
I don't see `--has-parallel4` option for `nc-config`.

**Comment by markjolah** [comment]
Thanks for taking the initiative.  I think that looks good.   Some notes:
1. Good point about this being for NetCDF4 only.  In that light I think the check for --has-pnetcdf flag check should be removed as that is a NetCDF v3 only property?  Anyways it is redundant as --has-paralell would already be true if --has-pnetcdf is true.  Unless there are some quirks to netcdf I'm unaware of.
2. I just checked and the --has-paralell4 flag which is what we really want is only available in netcdf-4.7.0 we are currently using 4.6.1 in the jedi-stack containers but may update soon.
3. My thought is then that we should check first for --has-paralell4 flag since that is the most directly relevent, and if the flag is not found then check for --has-parallel.  This will be forwards and backwards compatible.

**Comment by markjolah** [comment]
Clicked the wrong button.  Reopen.

**Comment by markjolah** [comment]
On a broader note.  Neither Mark M. nor myself have been able to compile the whole JEDI stack with the development  (v3.0.0) or master (v.2.10.2) branches of ecbuild at the moment.  Are you actually using the ecbuild develop branch?  The newest version that seems stable for us is 2.9.4.  It's probably going to be a process to get all our dependencies working with the upstream develop branch.  We're going to make a decision about how to proceed once everyone is back from the conference next week, but we'll probably just merge this file into the new "stable" branch at that point.

**Comment by aerorahul** [comment]
@markjolah I have not been using the develop or master of ecbuild.  These changes are placed on a local checkout of v2.9.3 on discover where the original findnetcdf.cmake is not sufficient.
I will make changes you suggested in 3 above.

**Comment by aerorahul** [comment]
@markjolah I have no issues with where this work is merged; `stable` or `develop`.  Since this change is orthogonal to the issues in versions > 2.9.4, would it be possible to merge in both `stable` and `develop`?

I have not been following the discussion on `ecbuild` issues in versions > 2.9.4.  

Something to note is that at NASA, we will begin using `ecbuild` for (configuring and) building the GEOS model, and probably want to start with a branch from `develop`, unless it is unadvisable.  We will be using this JCSDA fork of `ecbuild`

**Comment by markjolah** [comment]
Just saw the commit.  Looks good, but can we add the the check for --has-parallel in the else() branch of the the check for --has-paralell4.  I've included a commit.  It seems to work for me.  I left a note about a possible corner case with NetCDF<4.7.0 and pnetcdf is installed but HD5 was not built with mpi support. In this case we will return NETCDF_IS_PARALLEL=TRUE, which may be misleading but I see no easy way to fix it, and it is a strange case anyways, and has more to do with the way ecbuild is not coordinating the FindNetCDF3 and FindNetCDF4 files correctly (FindNetCDF3 doesn't even set the NETCDF_IS_PARALELL variable)

**Comment by markjolah** [comment]
As for the larger question of ecbuild versions, I think the idea is for us to also move to the upstream v3.0.0 development branch eventually.  Just for the moment we have a small but possibly unknown set of blocker bugs which will keep us at 2.9.x until we can test on all the relevant environments.  And yes I think we'll just merge this file (and similar upcoming fixes to FindLAPACK and FindMPI) into both our "stable" and "development" branches.

**Comment by aerorahul** [comment]
@markjola Thanks for the additional changes. They look good.
All good to go from me.

**Comment by markjolah** [comment]
OK.  I think this is ready to merge, but since everyone else here is still in DC, I'm going to wait until I get approval from someone more senior regarding our general plan with this repo and branches.  Hopefully we'll merge early next week and get it into the stable branch too.

**Comment by mmiesch** [comment]
So I'm getting this error when I try to build ufo-bundle - it happens also in develop:
~~~~~
-- ---------------------------------------------------------
-- Bundle ufo-bundle
-- ---------------------------------------------------------
CMake Error at /opt/modules/core/ecbuild/jcsda-develop/share/ecbuild/cmake/ecbuild_install_project.cmake:108 (string):
  string sub-command REPLACE requires at least four arguments.
~~~~~
Has anyone seen this before?  I don't think we ever touched that part of the code so I don't know what it's complaining about.

Also - I do not like the idea of a ```stable``` branch.  If we follow the git-flow paradigm, then the ```develop``` branch should be stable - it should pass all tests and it should be usable.  Any beta-testing should be done in feature branches.

**Comment by aerorahul** [comment]
@mmiesch I don't see that error message from `feature/netcdf4-cmake` when building OOPS, but I do see it when building a bundle.

`ecbuild_project.cmake` was added with #4d8e356, and is not present in any of the tags.
`ecbuild_bundle.cmake` was updated on how it descends down into sub-projects.

I fear `ecmwf:ecbuild/develop` is broken, or we don't know how to update our existing bundles to properly use them.

**Comment by markjolah** [comment]
So the error Mark sees results from the move of the upstream develop branch to v3.0.0.  Part of the new infrastructure introduced in v3.0.0 is to require all ecbuild projects to use the newer version of the CMake "project" command: https://cmake.org/cmake/help/latest/command/project.html

In particular, ecbuild now requires all packages provide a "VERSION" field in the project command.  Almost none of the JCSDA projects are currently doing this.  When no version is supplied the logic in several places in the new ecbuild v3.0.0 code breaks down and one of those places results in the error message Mark saw.  This specific error can be patched quite simply, but I get stuck on additional problems after I patch that one.

Also Mark, I hear you regarding the correct workflow paradigm and naming, but we have the problem that both upstream "master" (v2.10.2) and upstream "develop" (v3.0.0) branches track versions of ecbuild that cannot currently build the JCSDA stack which requires <=2.9.4 with all packages it their current state.

With some work we can probably get upstream master (v2.10.2) working for the jedi-stack, but it will take some testing to ensure that works on all platforms.  The goal of v3.0.0 will be a little more difficult as nearly every package will require at least some small changes to the CMakeLists.txt.  Also with v3.0.0 the minimum CMake necessary has increased from 2.8.4 to 3.6.0.  While this is not necessarily a bad thing, as it allows the use of newer CMake features, it will pose a problem for anyone building outside of the containers especially on HPC systems or older system images / VMs which often have very outdated CMake versions installed.

If we want to use the "develop" branch of our local ecbuild repo anytime soon we need to revert it back to 2.9.4, and have a policy to not pull from upstream until we are ready for their new version.  Otherwise we need to pick a new name which is where my idea for "stable" originated.

**Comment by markjolah** [comment]
Also today I spoke with Ward Fisher at Unidata who is the NetCDF project lead and wrote the CMake build system for NetCDF.  He's interested in us submitting a PR with our version of FindNetCDF.cmake, as it is something they have been planning to add in future versions but don't currently have the resources to accomplish.  I told him we'd be in touch after we made some progress testing on various systems.

**Comment by mmiesch** [comment]
Thanks @aerorahul for the description.  No urgency on my part - I was just trying to use ufo-bundle to check the two pull requests to see if the new Find netcdf and mkl works on aws.  Good to know that this is only a problem at the bundle level - I will test the two PRs by just building the oops repo tomorrow.

**Comment by markjolah** [comment]
OK.  We're going to move forward with the plan.  Only change is we'll maintain a "develop" branch and a "feature/stable" branch to match the git flow naming conventions.  We'll continue to pull appropriate PR's into both branches so that updates are available in "feature/stable" for immediate use, and in "develop" for testing.  The idea is that "feature/stable" will be merged with "develop" eventually after all the dependent repos have been updated and tested.

**Pull request merged**
