### PR TITLE
Bugfix/intel shlib undefined

### PR DESCRIPTION
**Pull request by markjolah**
This fix will address linking issues with Intel 17 and Intel 18 compilers on systems with binutils<2.28.  The symptom is failed linking with missing hidden symbol, normally in fckit:
```
/opt/intel/18/compilers_and_libraries_2018.3.222/linux/mpi/intel64/bin/mpiifort      -Wl,--disable-new-dtags    -Wl,--allow-shlib-undefined -O3 -DNDEBUG -unroll -inline -heap-arrays 32 CMakeFiles/fckit_test_shared_ptr.dir/test_shared_ptr.cc.o CMakeFiles/fckit_test_shared_ptr.dir/test_shared_ptr_main.F90.o  -o fckit_test_shared_ptr -Wl,-rpath,/home/molah/bundles/fv3-bundle/_build_ecmwf/lib ../../../lib/libfckit.so ../../../lib/libeckit_geometry.so ../../../lib/libeckit_linalg.so ../../../lib/libeckit_maths.so -lmkl_intel_lp64 -lmkl_sequential -lmkl_core ../../../lib/libeckit_web.so ../../../lib/libeckit_cmd.so -lcurses /usr/lib64/libform.so ../../../lib/libeckit_mpi.so ../../../lib/libeckit.so /usr/lib64/libssl.so /usr/lib64/libcrypto.so /usr/lib64/libcurl.so /usr/lib64/librt.so /usr/lib64/libm.so -ldl -lmpicxx -lirng -ldecimal -lcilkrts -lstdc++ 
ld: fckit_test_shared_ptr: hidden symbol `__intel_cpu_features_init_x' in /opt/intel/18/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
ld: final link failed: Bad value
```

This addresses the same problem as [JCSDA/ecbuild/bugfix/old-linker](https://github.com/JCSDA/ecbuild/tree/bugfix/old-linker) but we use CMake generator expressions to only disable the flags for Intel 17 and Intel 18 compilers.

There is more than one way to accomplish this.  With CMake generator expressions the test for broken linker and warning is still displayed but the generator expressions will evaluate to empty if Intel 17 or 18 compilers are used.  An alternate implementation would use an `if()` command together with CMAKE_<LANG>_COMPILER_ID and CMAKE_<LANG>_COMPILER_VERSION variables to disable the whole check.  Neither method was particularly succinct, but I think this is the best that can be done given the tools CMake provides.

This patch can be tested on discover (Intel 17 and ld 2.23) and S4 (Intel 18 and ld 2.27) which both suffer from the build issues

### CODE REVIEW

**Comment by mmiesch** [comment]
This is doing weird things for me on S4.  When I run ecbuild with intel17/impi it hangs here:
~~~~~

-- ---------------------------------------------------------
-- [eckit] (1.4.0) [1a44679]
~~~~~

And then if I ```^C``` out of this, my terminal is garbled.  This does not happen with bugfix/old-linker.  Not sure what is going on.

**Comment by markjolah** [comment]
OK. I will investigate.  I didn't get to test this much, just wanted to get it pushed, as its been sitting in my local repo for a bit.

**Comment by markjolah** [comment]
OK. Ready for a re-review on this PR.

**Comment by mmiesch** [comment]
Sorry - I missed that this was ready for re-review - I'll test it now

**Comment by mmiesch** [comment]
I tested this on the two main problem platforms, namely S4 and the (ubuntu 16) intel 17 container and all seems well.  Thanks @markjolah - as with all ecmwf forks, we should push this upstream with a PR there.

**Pull request merged**
